"""basic init

Revision ID: 773d67fb8a72
Revises: 
Create Date: 2023-03-30 15:05:35.913086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '773d67fb8a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enum_field', sa.Enum('A', 'B', 'C', name='simpleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_model')
    # ### end Alembic commands ###
