name: Test Enum Migrations
on: push

jobs:
  test_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sqlalchemy: ["1.4.46", "2.0.7"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: pip install -e . && pip install -e test-harness

      - name: Install explicit sqlalchemy
        run: pip install sqlalchemy==${{ matrix.sqlalchemy }}

      - name: Run test harness
        run: cd test-harness && pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: "postgres"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"

  publish_python_package:
    name: Publish python package

    runs-on: ubuntu-latest

    needs: [test_job]
    if: ${{ startsWith(github.ref, 'refs/tags/') && always() && !cancelled() && !contains(needs.*.result, 'failure') }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install poetry
        run:
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build sdist static artifact
        run: |
          poetry install
          poetry build
      - name: Publish
        run: |
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}

