name: Test Enum Migrations
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -e . && pip install -e test-harness

      - name: Connect to PostgreSQL
        run: cd test-harness && pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: "postgres"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
